version: '3.8'

services:
  maven:
    build: maven
    volumes:
      - "build:/home/boxfuse-sample-java-war-hello/target"

  tomcat:
    image: tomcat:8.0-slim
    ports:
      - "8081:8080"
    volumes:
      - "build:/usr/local/tomcat/webapps"

volumes:
  build: