version: '3.8'

services:
  maven:
    build: maven
    volumes:
      - type: volume
        source: build
        target: /home/boxfuse-sample-java-war-hello/target

  tomcat:
    image: tomcat:8.0-slim
    ports:
      - "81:8080"
    volumes:
      - type: volume
        source: build
        target: /usr/local/tomcat/webapps

volumes:
  build: