---
- name: install nginx
  hosts: web
  become: yes

  tasks:
  - name: nginx is present
    apt:
      name: nginx
      state: present

  - name: index.html is present
    copy:
      src: index.html
      dest: /var/www/html

  - name: nginx is started
    service:
      name: nginx
      state: started

- name: install db
  hosts: db
  become: yes

  tasks:
  - name: postgresql is present
    apt:
      name: postgresql
      state: present

  - name: postgresql is started
    service:
      name: postgresql
      state: started
